stages:
  - deploy
    
deploy_staging:
  stage: deploy
  type: deploy 
  script:
    - ssh -i /home/gitlab-runner/devops.pem ubuntu@13.213.248.9 -T "/home/ubuntu/docker/dts-fe/dts-fe.sh dev"
    #- echo "Auto Deploy is disabled, please deploy mannual using dts-fe.dev sh"  
  only:
    - development 